-- Table: public.datos

-- DROP TABLE IF EXISTS public.datos;

CREATE TABLE IF NOT EXISTS public.datos
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    fechadata timestamp(0) without time zone NOT NULL,
    fechasys timestamp(0) without time zone NOT NULL,
    equipo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tag character varying(50) COLLATE pg_catalog."default" NOT NULL,
    valor numeric(20,6) NOT NULL,
    CONSTRAINT online_fechadata_equipo_tag_1cef2062_uniq UNIQUE (fechadata, equipo, tag)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.datos
    OWNER to admin;
-- Index: datos_idx

-- DROP INDEX IF EXISTS public.datos_idx;

CREATE INDEX IF NOT EXISTS datos_idx
    ON public.datos USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: online_timestamp_idx

CREATE INDEX IF NOT EXISTS datos_fecha_idx
    ON public.online USING btree
    (fechadata ASC NULLS LAST, equipo COLLATE pg_catalog."default" ASC NULLS LAST, tag COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: datos_timestamp_idx

-- DROP INDEX IF EXISTS public.datos_timestamp_idx;

CREATE INDEX IF NOT EXISTS datos_timestamp_idx
    ON public.datos USING btree
    (fechadata DESC NULLS FIRST)
    TABLESPACE pg_default;
